version: '3'
services:

  #PHP Service
  app:
    build: ./php
    container_name: app_parking_api
    restart: unless-stopped
    platform: linux/amd64
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    extra_hosts:                            # <--- this is required
      - "host.docker.internal:host-gateway" # <--- this is required

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_parking_api
    restart: unless-stopped
    ports:
      - "8190:80"
      - "23527:23517"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    extra_hosts: # <-- does no harm
      - "host.docker.internal:host-gateway" # <-- does no harm

  #MySQL Service
  db:
    image: mysql:8.1
    platform: linux/amd64
    container_name: db_parking_api
    restart: unless-stopped
    ports:
      - "3341:3306"
    environment:
      MYSQL_DATABASE: parking_api
      MYSQL_USER: parking_api
      MYSQL_PASSWORD: parking_api
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata_parking_api:/var/lib/mysql/
    networks:
      - app-network

  testdb:
    image: mysql:8.1
    platform: linux/amd64
    container_name: db_parking_api_test
    restart: unless-stopped
    ports:
      - "3342:3306"
    environment:
      MYSQL_DATABASE: parking_api_test
      MYSQL_USER: parking_api_test
      MYSQL_PASSWORD: parking_api_test
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata_parking_api_test:/var/lib/mysqltest/
    networks:
      - app-network

  swagger-editor:
    image: swaggerapi/swagger-editor
    platform: linux/amd64
    container_name: "swagger-editor-trading"
    ports:
      - "8091:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    platform: linux/amd64
    container_name: "swagger-ui-trading"
    ports:
      - "8092:8080"
    volumes:
      - ./swagger.yaml:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
      #API_URL: "127.0.0.1"

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mysqldata_parking_api:
    driver: local
  mysqldata_parking_api_test:
    driver: local