<?php

namespace App\Repositories;

use App\Repositories\Contracts\MembershipInterface;

class MembershipRepository extends EloquentBaseRepository implements MembershipInterface
{
    public function update(\ArrayAccess $model, array $data): \ArrayAccess
    {
        $data['points'] = $model->points + 5;
        return parent::update($model, $data); // TODO: Change the autogenerated stub
    }
}
