<?php

namespace App\Repositories;

use App\Repositories\Contracts\InstrumentSupportedRepository;
use App\Repositories\Contracts\ParkingInterface;
use App\Repositories\Contracts\PlaceInterface;
use App\Repositories\Contracts\UserInterface;

class ParkingRepository extends EloquentBaseRepository implements ParkingInterface
{
    public function save(array $data): \ArrayAccess
    {
        $data['barcode'] = uniqid();
        $data['in_time'] = now();
        return parent::save($data); // TODO: Change the autogenerated stub
    }
}
